import { useState } from "react";
import {
  Stepper,
  Text,
  Grid,
  Container,
  Title,
  Divider,
  Group,
} from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import { usePrompts } from "../context/PromptContext";
import { NEW_PROMPT_CATEGORIES } from "../write/interface";
import {
  PiNumberFourBold,
  PiNumberOneBold,
  PiNumberThreeBold,
  PiNumberTwoBold,
} from "react-icons/pi";

interface HowItWorksProps {
  answerQ2?: string;
}

export function HowItWorks({ answerQ2 }: HowItWorksProps) {
  const { prompts } = usePrompts();
  const [activeStep, setActiveStep] = useState(0);
  const isSmallScreen = useMediaQuery("(max-width: 1000px)");

  // Mapping of quiz results to category titles
  const categoryMap: Record<string, string[]> = {
    A: ["Inner Thoughts", "Gratitude Moments", "Confidence Boost"],
    B: ["Creative Spark", "Adventure Tales", "Future Dreams"],
    C: ["Calm Vibes", "Feel-Good Fun", "Playtime Ideas"],
    D: ["Brain Puzzles", "Empathy Challenge"],
  };

  // Filter categories based on quizResult or use default prompts
  const filteredCategories = NEW_PROMPT_CATEGORIES.filter((category) =>
    categoryMap[answerQ2]?.includes(category.title)
  );

  const displayPrompts =
    filteredCategories.length > 0
      ? prompts
          .filter((prompt) =>
            filteredCategories.some(
              (category) => category.title === prompt.category
            )
          )
          .map((prompt) => prompt.text)
      : prompts.map((prompt) => prompt.text);

  return (
    <Container size="lg" content="center">
      <Group pt="xl">
        <Divider flex={1} />
        <Title ta="center" order={1}>
          How It Works
        </Title>
        <Divider flex={1} />
      </Group>

      <Text ta="center" c="dimmed" mb="xl">
        Start with ease, find inspiration fast, and let your creativity flow
        freely
      </Text>

      <Grid gutter={50} align="flex-start" pt="xl">
        {/* Stepper on the left */}
        <Grid.Col span={{ base: 12, md: 3 }}>
          <Stepper
            active={activeStep}
            onStepClick={setActiveStep}
            orientation={isSmallScreen ? "horizontal" : "vertical"}
            iconSize={32}
          >
            <Stepper.Step
              label="Choose a Prompt"
              description="Find your inspiration"
              icon={<PiNumberOneBold size={16} />}
            />
            <Stepper.Step
              label="Start Writing"
              description="Let your creativity flow"
              icon={<PiNumberTwoBold size={16} />}
            />
            <Stepper.Step
              label="Use AI Assistance"
              description="Overcome writer's block"
              icon={<PiNumberThreeBold size={16} />}
            />
            <Stepper.Step
              label="Review and Analyze"
              description="Get insights on your writing"
              icon={<PiNumberFourBold size={16} />}
            />
          </Stepper>
        </Grid.Col>

        {/* Step content and image on the right */}
        <Grid.Col span={{ base: 12, md: 9 }}>
          <Grid gutter={30}>
            <Grid.Col span={12}>
              {activeStep === 0 && (
                <div>
                  <Title order={3}>Choose a Prompt</Title>
                  <Text mt="md" c="dimmed">
                    Begin by selecting a prompt that sparks your interest. You
                    can generate a random prompt, browse categories tailored to
                    your mood, or search through the list to find the perfect
                    match. There’s always something to ignite your creativity.
                  </Text>
                </div>
              )}

              {activeStep === 1 && (
                <div>
                  <Title order={3}>Start Writing</Title>
                  <Text mt="md" c="dimmed">
                    Dive into the writing experience with a simple text editor.
                    Focus on your ideas and let your thoughts flow naturally. As
                    you write, you'll see helpful statistics at the bottom of
                    the page, giving you a sense of progress.
                  </Text>
                </div>
              )}

              {activeStep === 2 && (
                <div>
                  <Title order={3}>Use AI Assistance</Title>
                  <Text mt="md" c="dimmed">
                    If you get stuck, AI can help generate the next sentence.
                    Once you've written at least 100 characters, use AI to
                    overcome writer’s block and keep your story moving forward.
                    See which parts are AI-generated by hovering over the
                    lightbulb icon.
                  </Text>
                </div>
              )}

              {activeStep === 3 && (
                <div>
                  <Title order={3}>Review and Analyze</Title>
                  <Text mt="md" c="dimmed">
                    When you submit your writing, you'll receive detailed
                    insights, including writing time, unique word percentage,
                    and other metrics. AI feedback covers five categories: mood,
                    relevance, creativity, completeness, and readability.
                    Explore your word frequency in a word bubble chart to see
                    the most commonly used words in your writing.
                  </Text>
                </div>
              )}
            </Grid.Col>

            {/* Placeholder for an image */}
            <Grid.Col span={12}>
              <div style={{ textAlign: "center" }}>
                {/* Add an image here if desired */}
                {/* <img
                  src="/path/to/your/image.png"
                  alt="Writing Insights"
                  style={{ maxWidth: "100%", height: "auto" }}
                /> */}
              </div>
            </Grid.Col>
          </Grid>
        </Grid.Col>
      </Grid>
    </Container>
  );
}
