export const data_2 = [
  "Imagine animals could draw—what kind of artwork would a cat create?",
  "If clouds had thoughts, what would they think about as they float through the sky?",
  "What’s a small habit you’ve developed recently that has made your day a little brighter?",
  "What’s a recent experience that made you feel more like yourself?",
  "What’s one natural sight that never fails to make you smile?",
  "What’s something you own that always makes you feel comforted?",
  "What's a song that you loved and what did you love about it?",
  "What’s one sensory experience that always makes you feel calm?",
  "What’s your ideal way to spend a quiet evening?",
  "If you could design your own amusement park, what would be the theme?",
  "What kind of treasure would you hope to find on a hidden adventure?",
  "If you could create a brand-new holiday, what would it celebrate?",
  "Design a gadget that helps people wake up in the morning feeling energized.",
  "What’s a creative solution to help people remember their keys?",
  "How would you rearrange a typical grocery store to make shopping more fun?",
  "What’s a talent or skill you have that makes you feel unique?",
  "What’s something you’ve done that you once thought was impossible?",
  "What’s a personal trait that you know others admire in you?",
  "Imagine you’re a tree in a busy park—how do you feel watching people come and go?",
  "What’s one thing you think a stranger on the street you saw might be worried about today?",
  "How do you think the moon feels watching over the Earth every night?",
  "What’s one futuristic invention you wish existed right now?",
  "If you could spend a week in the future, what’s the first thing you’d want to see?",
  "What’s a positive change you hope to see in the world 50 years from now?",
  "You’ve been granted the power to speak to mythical creatures—what’s the first creature you talk to?",
  "You’re stranded on a deserted island, but you have one magical item with you—what is it?",
  "What’s a habit you admire in others that you want to adopt?",
  "If you could give yourself a motivational quote, what would it be?",
  "You discover a single use time machine. Do you go forward in time or backward in time and how far? What do you hope to see?",
  "Imagine if a turtle could sing - what would the turtle sing about?",
  "If flowers had personalities, what would their conversations sound like as they bloom in the garden?",
  "What’s a hobby or activity that never fails to make you happy?",
  "What’s a memory that instantly brings a smile to your face?",
  "Imagine a giant box is delivered to your front doorstep with your name on it. What's inside and what happens when you open it?",
  "Which is better, winter or summer? Describe the reasons why you think winter or summer is better.",
  "If you could have any secret super power, what would you want it to be and why?",
  "You've been shrunk down to be only 1\" tall by an evil wizard. How would your life change, and would you try to fix it?",
  "If you were in charge of the whole world, what would you do to make the world a happier place?",
  "Imagine every human had a photographic memory—how would that change education and knowledge-sharing?",
  "What’s one hurdle you believe every human overcomes at some point in life?",
  "How will the concept of work will change in the future?",
  "You’ve discovered a secret door in your home that leads to a different dimension—what’s the first thing you encounter on the other side?",
  "A mysterious book allows you to enter any story ever written—where do you go, and what role do you play in that world?",
  "You wake up one day, and gravity has shifted—what’s the first adventure you embark on in this new reality?",
  "Do you prefer the sunrise or sunset? What are your favorite parts?",
  "What is a sound you usually hear that could actually make a good beat? What would the song be about?",
  "Imagine sitting by some water. Where are you and why do you think you are there?",
  "What do you like about the taste of your favorite drink?",
  "What’s a clever solution to help people remember names better in social settings?",
  "You are the security guard at the zoo and someone has stolen a rhinoceros! How do you track down the thief?",
  "Imagine you are the captain of a pirate ship. What would today's diary entry look like?",
  "If you were tasked with organizing a large outdoor event, how would you ensure that everyone can easily navigate and find what they need?",
  "Design a low-cost way to help people stay hydrated throughout the day.",
  "If you could open your own restaurant, what would the signature dish be, and what would make it stand out?",
  "If you could create a new school subject based on something you're passionate about, what would it teach, and how would you teach it?",
  "What’s one way you could be kinder to yourself when things don’t go as planned?",
  "What’s a skill you’ve always wanted to develop, and what’s one thing you can do today to start learning it?",
  "If you could focus on improving just one aspect of your life over the next month, what would it be, and why?",
  "What’s a quality you admire in yourself that you want to strengthen, and how will you nurture it?",
  "What’s a small victory you’ve recently achieved, and how can you build on that success?",
  "How will humans build and maintain friendships in the future?",
  "If you could ask your future self one question, what would it be, and why?",
  "If you could design a futuristic city, what would be the most important feature to improve quality of life?",
  "You’re the last slice of pizza at a party—how do you feel as everyone debates whether to take you?",
  "You are a street musician - how does it feel when someone pauses to listen and smiles?",
  "What was a street mural you saw recently and what is the artist's motto in life?",
  "What would you see if you were a local bird?",
  "Last time your achieved your goal, how did you reward yourself?",
  "What’s a belief you hold about life that helps guide your decisions?",
  "What’s the new activity or hobby that has brought some unexpected happiness into your life?",
  "What’s a personal tradition or ritual that always brings you joy when you do it?",
  "What are some similarities and differences with 10 year old you?",
  "What’s something you’ve created or accomplished that always makes you feel a little bit like a superhero?",
  "What’s a moment where you surprised yourself by doing something you never thought you could?",
  "Think to exactly a year back from today - what is one way you’ve grown over the past year that makes you feel like you’re becoming your best self?",
  "What’s a moment when you realized how strong you really are, both mentally and emotionally?",
  "What’s one meal or food that always brings you comfort, and why does it hold a special place for you?",
  "What’s a piece of technology or invention you’re thankful for, and how does it improve your life?",
  "What’s one piece of advice you’ve received that you’re grateful for and that has stuck with you?",
  "What if every human could see emotions as colors—how would that affect our communication?",
  "If money was no object, what would you spend your days doing?",
  "What are three qualities you admire in others, and how do you embody them?",
  "If you discovered a hidden room in your house filled with items from your dreams, what would you find?",
  "What would happen if the trees could whisper their secrets to anyone who stopped to listen?",
  "If you could trade places with any fictional character for a day, who would you choose and what adventures would you embark on?",
  "If you could invent a brand new color that doesn’t exist yet, what would you name it and how would you describe it?",
  "If you could invent a device that makes learning new skills faster, what would it be and how would it work?",
  "If you had to create a new board game, what would the theme be and how would players win?",
  "What would be an innovative way to encourage people to take breaks during their workday?",
  "What is your favorite scent that brings you a sense of peace, and why does it resonate with you?",
  "If you could create your perfect calm retreat, what elements would you include and how would they contribute to your tranquility?",
  "Imagine you are a cozy blanket – how do you make someone feel warm and safe?",
  "If you were a character in a children's book, how would you help a child learn something new?",
  "If you were to create a calming playlist, which three songs would you include and why?",
  "Can you recall a time when you felt truly proud of yourself? What did you achieve?",
  "Who is someone in your life that inspires you to be your best self? How do they impact your confidence?",
  "What is a positive mantra or affirmation you can say to yourself to boost your confidence?",
  "What is one piece of advice you would give to someone struggling with their self-esteem?",
  "If you could create a new tradition for future generations, what would it be?",
  "What environmental change do you hope to see in the future that would benefit our planet?",
  "What legacy do you wish to leave behind that could inspire future generations?",
  "What is a talent or skill you possess that you are proud of and how did you discover it?",
  "Can you recall a time when you helped someone else see their own worth? What did you say?",
  "Can you describe a situation where you took a risk that turned out to be empowering?",
  "What qualities do you admire in others that you also possess?",
  "If you could create a new sport that combined elements from any activities you enjoy, what would it be and how would it be played?",
  "What would happen if laughter was a visible force that changed colors depending on how funny a joke is? What colors would you see?",
  "If you could invent a new flavor of ice cream, what would it be and what unique ingredients would you use?",
  "If you could have any animal as a pet, regardless of size or rarity, what would you choose and how would you care for it?",
  "What would happen if clouds were made of candy? Describe a day where you could interact with them.",
  "If you could design an outfit made entirely of your favorite materials, what would you choose and how would it feel to wear it?",
  "Imagine you found a magic paintbrush that brings your drawings to life. What would you draw first, and why?",
  "If you could turn any activity into an Olympic sport, what would it be, and how would it be played?",
  "Who is someone in your life that you are thankful for, and what is a cherished memory you have with them?",
  "What’s an unexpected compliment you received that made you appreciate yourself more?",
  "What’s a hobby or activity that brings you immense joy, and how do you feel when you engage in it?",
  "What’s a favorite food that brings you joy and reminds you of happy moments?",
  "Who is someone in your life that always makes you laugh, and how do they do it?",
  "What’s a lesson you learned from a failure that you are thankful for now?",
  "If you could write a letter to your past self, what encouraging advice would you give?",
  "What song lyric or quote resonates with you, and how does it connect to your life?",
  "What is one thing you appreciate about your current life situation that brings you joy?",
  "What is a passion project or interest that you’ve always wanted to explore but haven’t yet?",
  "What is one question about your future that excites you the most and why?",
  "What makes your favorite movie unique?",
  "If you could be an expert in any field, what would it be and what do you do?",
  "Picture your dream cozy space. What elements are essential for you to feel relaxed and at home?",
  "If everyday objects could talk, which one would have the most fascinating stories to tell?",
  "Imagine if you woke up one day with the ability to communicate with one element of nature—what would it be and what would you ask?",
  "What would your dream treehouse look like, and what special features would it have for fun activities?",
  "Imagine a day where everyone can wear hats that reflect their mood. What would your hat look like today?",
  "If success was guaranteed, what dream would you choose to pursue and why?",
  "What do you want to be remembered for?",
  "What kinds of problems do you enjoy solving?",
  "What’s something you have lost sleep over? Why?",
  "Think of a person you know. How can you tell if this person is happy or sad?",
];

export const data = [
  "happiness",
  "rain",
  "curiosity",
  "mountain",
  "laughter",
  "creativity",
  "dolphin",
  "art",
  "knowledge",
  "anger",
  "river",
  "freedom",
  "car",
  "kindness",
  "music",
  "trust",
  "compass",
  "cloud",
  "puzzle",
  "jealousy",
  "moon",
  "book",
  "emotion",
  "tree",
  "gold",
  "imagination",
  "sadness",
  "fire",
  "robot",
  "love",
  "poetry",
  "science",
  "ocean",
  "fear",
  "sunshine",
  "friendship",
  "eagle",
  "time",
  "light",
  "mystery",
  "wisdom",
];
