import {
  FaBalanceScale,
  FaBook,
  FaBrain,
  FaBullseye,
  FaCog,
  FaCompass,
  FaExclamationCircle,
  FaEye,
  FaFlag,
  FaHeart,
  FaLightbulb,
  FaMagic,
  FaPencilAlt,
  FaQuestion,
  FaRegClock,
  FaRunning,
  FaStar,
  FaStepForward,
  FaUserGraduate,
} from "react-icons/fa";

export const profileQuizQuestions = [
  {
    label: "Word Count",
    icon: FaBullseye,
    text: "Choose your target word count:",
    question: "targetWordCount",
    options: [
      {
        value: "100",
        label: "Quick (100 words)",
        description: "Quick entry to get your thoughts down.",
        icon: FaRegClock,
      },
      {
        value: "250",
        label: "Standard (250 words)",
        description: "Standard entry to get your thoughts down.",
        icon: FaBook,
      },
      {
        value: "500",
        label: "Detailed (500 words)",
        description: "Detailed entry to get your thoughts down.",
        icon: FaRunning,
      },
      {
        value: "750",
        label: "Extensive (750 words)",
        description: "Extensive entry to get your thoughts down.",
        icon: FaBook,
      },
      {
        value: "custom",
        label: "Custom",
        description: "Tailor your entry to your specific needs.",
        icon: FaCog,
      },
    ],
  },
  {
    label: "AI Style",
    icon: FaBrain,
    text: "Select your preferred AI persona:",
    question: "feedbackPersona",
    options: [
      {
        value: "gentle",
        label: "Cheerleader",
        description: "Celebrate wins and encourage progress.",
        icon: FaHeart,
      },
      {
        value: "balanced",
        label: "Coach",
        description: "Blend praise with helpful guidance.",
        icon: FaBalanceScale,
      },
      {
        value: "critical",
        label: "Critic",
        description: "Give direct, detailed advice for fast improvement.",
        icon: FaExclamationCircle,
      },
      {
        value: "inspirational",
        label: "Muse",
        description: "Spark creativity and inspire exploration.",
        icon: FaMagic,
      },
      {
        value: "efficient",
        label: "Editor",
        description: "Offer quick fixes to polish your writing.",
        icon: FaPencilAlt,
      },
      {
        value: "reflective",
        label: "Mentor",
        description: "Focus on growth with thoughtful insights.",
        icon: FaUserGraduate,
      },
    ],
  },
  {
    label: "Feedback Type",
    icon: FaLightbulb,
    text: "What feedback style motivates you?",
    question: "motivatingFeedback",
    options: [
      {
        value: "clear goal",
        label: "A clear goal",
        description: "Set a target to guide your improvement.",
        icon: FaFlag,
      },
      {
        value: "actionable step",
        label: "An actionable step",
        description: "Get advice you can use immediately.",
        icon: FaStepForward,
      },
      {
        value: "question",
        label: "A question to explore",
        description: "Inspire creativity with thought-provoking questions.",
        icon: FaQuestion,
      },
      {
        value: "strengths",
        label: "Highlight strengths",
        description: "Learn what’s working well and how to build on it.",
        icon: FaStar,
      },
      {
        value: "new perspective",
        label: "A new perspective",
        description: "See your work from a fresh angle.",
        icon: FaEye,
      },
      {
        value: "big picture",
        label: "The big picture",
        description: "Connect your work to a broader purpose.",
        icon: FaCompass,
      },
    ],
  },
];
